config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :speeches

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :speech
  monetize :amount_cents
end

app/models/speech.rb
class Speech < ApplicationRecord
  belongs_to :user
  belongs_to :training
  has_one_attached :audio, dependent: :destroy
  has_many :orders, dependent: :destroy

  # validates :title, format: { with: /[a-zA-Z0-9]/, message: "must be in English only" }, presence: true

  validates :transcript, format: { with: /[a-zA-Z0-9]/, message: "must be in English only" }, presence: true

  validates :notes, format: { with: /[a-zA-Z0-9]/, message: "must be in English only" }, presence: true


  # with_options presence: true, format: { with: /[a-zA-Z0-9]/, message: 'Plese use English only' } do
  #   validates :title
  #   validates :transcript
  #   validates :notes
  # end


  # validates :status, presence: true
  # Not using this anymore
  enum status: {
    "Normal (24 hours - 5円/s)": 0,
    "Fast (18 hours - 7円/s)": 1,
    "Faster (12 hours - 9円/s)": 2,
    "Fastest (16 hours - 10円/s)": 3
  }

  def current_status
    if corrected_by_teacher?
      "Corrected by #{self.training.speeches.last.user.first_name}"
    elsif paid_order
      "Awaiting correction"
    else
      "Awaiting payment"
    end
  end
  # Let's rename these to be more clear
  # State machines
  # Dependency injection
  # Polymorphism - create classes that inherit from Speech
  def status_color
    if corrected_by_teacher?
      "recorded"
    elsif paid_order
      "paid"
    else
      "pending"
    end
  end

  def paid_order
    orders.find_by(state: 'paid')
  end

  def corrected_by_teacher?
    training.speeches.count.even?
  end

  PRICE_PER_SECOND = 5

  def seconds
    return 0 unless length

    (length.fdiv(1000)).round(0)
  end

  def total_price
    price = PRICE_PER_SECOND * seconds
    price < 50 ? 50 : price
  end

  # callback
  # before_validation :create_training

  # def create_training
  #   training = Training.create(user: user)
  #   self.training = training
  # end
end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_many :speeches

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :speeches
  has_many :payments
  has_many :trainings
  has_many :orders
  has_one_attached :photo, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password, :password_confirmation, :teacher])

    # For additional in app/views/devise/registrations/edit.html.erb

    # devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    speech = Speech.find(params[:speech_id])
    order  = Order.create!(speech: speech, amount: speech.total_price, state: 'pending', user: current_user)

    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: speech.title,
        images: [speech.user.photo],
        amount: speech.total_price,
        currency: 'jpy',
        quantity: 1
      }],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    order.update(checkout_session_id: session.id)
    authorize order
    redirect_to new_order_payment_path(order)
  end

  def show
    @order = current_user.orders.find(params[:id])
    authorize @order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
    authorize @order
  end
end

app/controllers/speeches_controller.rb
class SpeechesController < ApplicationController
  # skip_before_action :authenticate_user!
  def index
    @speeches = policy_scope(Speech).order(created_at: :desc)
  end

  def new
    @speech = Speech.new
    authorize @speech
    if current_user.teacher? && params["training"].present?
      @training = Training.find_by(id: params["training"].to_i)
    end
  end

  def show
    @speech = Speech.find(params[:id])
    authorize @speech
  end

  def create
    @speech = Speech.new(speech_params)
    @speech.user = current_user
    if params["training"].nil?
      @training = Training.new
      @training.user = current_user
      @speech.training = @training
    else
      @training = Training.find_by(id: params["training"].to_i)
      @speech.training = @training
    end
    authorize @speech
    if @speech.save
      redirect_to speech_path(@speech.training.speeches.first), notice: 'Your speech was saved successfully'
    else
      render :new, notice: 'Please try again, your speech could not be saved'
    end
  end

  def edit
  end

  def update
    @speech = Speech.find(params[:id])
    authorize @speech
    if @speech.update(speech_params)
      redirect_to speech_path(@speech), notice: 'Your speech was successfully updated.'
    else
      render :show
    end
  end

  def destroy
    @speech = Speech.find(params[:id])
    authorize @speech
    @speech.destroy
    redirect_to speeches_path, notice: 'Your speech was successfully deleted.'
  end

  private

  def speech_params
    params.require(:speech).permit(:title, :length, :notes, :transcript, :audio, :status)
  end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/application/_form.html.erb
<p>Form will go here later</p>

app/views/application/_new_thing.html.erb
<button type="button" class="btn btn-primary mx-3" data-bs-toggle="modal" data-bs-target="#exampleModal">
  New
</button>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New Form</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render 'form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/application/_speech_card.html.erb
<div class="container-card d-flex position-relative text-center">
  <div class="speech-card">
    <div class="speech-card-contents">
      <% if current_user.teacher? %>
        <div class="d-flex align-items-center justify-content-center mb-3">
          <div>
            <% if speech.user.photo.attached? %>
              <%= cl_image_tag speech.user.photo.key, class: "avatar-large mx-2" %>
            <% end %>
          </div>
          <div class="d-flex">
            <p class="text-wrap" style="max-width: 120px;"><%= speech.user.first_name %> <%= speech.user.last_name %></p>
          </div>
        </div>
      <% end %>
      <%= link_to speech.title.present? ? speech.title : "Response to #{speech.training.speeches[0].title}", speech_path(speech.id), class:"text-decoration-none speech-title" %>
      <p><%= pluralize speech.seconds, "second" %> &mdash; <%= speech.total_price %>円</p>
      <div class="row align-items-center">
        <div class="d-flex align-items-center justify-content-center">
          <% if speech.current_status.include?("Corrected by") %>
            <%= cl_image_tag speech.training.speeches.last.user.photo.key, class: "avatar-large my-2 mx-2" %>
          <% else %>
            <img src="https://www.nicepng.com/png/full/131-1314805_radio-spot-icon-mike-icons.png" class="avatar-large mx-2">
          <% end %>
          <h3 style="min-width: fit-content;"><span class="status-pill <%= speech.status_color %> ">
              <%= speech.current_status %></span>
          </h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_user_speech.html.erb
<div class="row my-1">
  <div class="col-12">
    <h2 class="text-center"> <%= speech.user.teacher? ? "Teacher speech" : "Student speech" %></h2>
  </div>
</div>
<div class="row" style="position:relative;">
  <div class="col col-md-4">
  </div>
</div>
<div class="row py-2">
  <div class="col col-12 col-md-4 text-center">
    <div class="shadow">
      <h5 class="fw-bold">Speech audio</h5>
      <% if current_user == speech.user %>
        <%= link_to "", speech_path(speech), data: { confirm: "Delete speech?" }, method: :delete, class: "far fa-trash-alt text-white speech-icon" %>
      <% end %>
      <div class="d-flex justify-content-start align-items-center">
        <% if speech.user.photo.attached? %>
          <%= cl_image_tag speech.user.photo.key, class: "avatar-large" %>
        <% end %>
        <p id="speech-title">
          <% if speech.title %>
            "<%= speech.title %>" by <%= speech.user.first_name%>
          <% else %>
            <%= speech.user.first_name%>'s response
          <% end %>
        </p>
      </div>
      <div class="d-flex align-items-center my-4">
        <audio controls src="https://res.cloudinary.com/dqco8z2dj/video/upload/<%= Rails.env %>/<%= speech.audio.key %>.webm"> </audio>
      </div>
      <div>
        <% if current_user == speech.user && !current_user.teacher && !speech.paid_order %>
          <%= form_tag orders_path do %>
            <%= hidden_field_tag 'speech_id', speech.id %>
            <%= submit_tag 'Make payment', class: "btn btn-primary text-white", id: "pay" %>
          <% end %>
        <% elsif current_user.teacher && speech.paid_order && !speech.user.teacher && !speech.corrected_by_teacher? %>
          <form action="/speeches/new">
            <input class="d-none" type="text" name="training" value=<%= @speech.training.id %>>
            <button class="btn btn-primary p-2 text-white" type="submit">Correct speech</button>
          </form>
        <% elsif current_user == speech.user && !current_user.teacher && speech.paid_order %>
          <h6 style="text-align: right;"><%= speech.total_price %>円</h6>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col col-12 col-md-4 text-center">
    <div class="shadow white">
      <h5 class="fw-bold">Transcript
        <% if current_user == speech.user %>
          <i class="fas fa-pencil-alt text-dark speech-icon" data-bs-toggle="modal" data-bs-target="#speech_transcript_<%=speech.id%>"></i>
        <% end %>
      </h5>
      <%= render 'speeches/edit_modal', id: "speech_transcript_#{speech.id}", speech: speech, transcript: true  %>
      <div class="w-100 my-2"><%= speech.transcript %></div>
    </div>
  </div>
  <div class="col col-12 col-md-4 text-center">
    <div class="shadow light">
      <h5 class="fw-bold">Notes
        <% if current_user == speech.user %>
          <i class="fas fa-pencil-alt speech-icon" data-bs-toggle="modal" data-bs-target="#speech_notes_<%=speech.id%>"></i>
        <% end %>
      </h5>
      <%= render 'speeches/edit_modal', id: "speech_notes_#{speech.id}", speech: speech, transcript: false  %>
      <div class="w-100 my-2"><%= speech.notes %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEnglishSpeech</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta >
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>
    <%# <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>
    <%# <meta name="twitter:title" content="<%= meta_title %>
    <%# <meta name="twitter:description" content="<%= meta_description %>
    <%# <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>
    <%# <meta name="twitter:image:src" content="<%= meta_image %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(	https://img.freepik.com/free-vector/payment-information-concept-illustration_114360-2886.jpg?w=1060);">
  <div class="container">
    <h1>Please confirm your payment</h1>
  </div>
</div>
<div class="container-order d-flex position-relative text-center">
  <div class="card-order">
    <div class="card-contents justify-content-center my-2 p-2 ">
      <%= image_tag "check.png"%>
      <p>Order #<%= @order.id %> </p>
      <span class="badge badge-primary"><%= @order.state %></span>
      <h2>Your payment successful!</h2>
      <div class="card-contents d-flex position-relative text-center">
        <div class="contentnts-list">
          <ul>
            <li class="row">
              <strong>Issued on: </strong><%= @order.created_at.to_date %>
            </li>
            <li class="row">
              <strong>Speech's title: </strong><%= @order.speech.title %>
            </li>
            <li class="row">
              <strong>Total: </strong><%= @order.speech.total_price %>円
            </li>
            <%#= @order.teddy_sku %>
          </ul>
        </div>
      </div>
    </div>
    <h2>Estimated delivery in <strong>1 business day</strong></h2>
    <h2>Thank you for your business!</h2>
  </div>
</div>
<div class="row-button">
  <div class="col-button">
  <%= link_to "Home", root_path, class: "btn btn-secondary col-6 mb-3" %>
  <%= link_to "Speeches", speeches_path, class: "btn btn-orange col-6 mb-3" %>
  <%= link_to "This speech", speech_path(@order.speech), class: "btn btn-purple col-6 mb-3" %>
  </div>
</div>
</div>

app/views/pages/home.html.erb
<div class="home-page" data-controller="hello">
  <%# Banner %>
  <div class="home-header">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12">
          <div class="hero-text-box">
            <h1>MyEnglishSpeech</h1>
            <h2>Your words, perfected</h2>
            <%= link_to "Record a speech", new_speech_path, class: "btn btn-full" %>
            <button class="btn btn-ghost" data-hello-target="button" data-action="click->hello#scrollDown">About this service</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%# What is MyEnglishSpeech? %>
  <section id="explanation" data-hello-target="title">
    <div class="container">
      <div class="row justify-content-center" id="overview" >
        <h2 >More than just translations</h2>
        <div class="row justify-content-center">
          <div class="col-sm-10">
            <p class="long-copy">
              When you need your English corrected, what can you do? If you don't have teacher or native speaker on hand, look no further than MyEnglishSpeech. Get corrections to your grammar and pronunciation so that your English sounds perfect!
            </p>
          </div>
        </div>
        <div class="row" id="icons">
          <div class="col-md-3 my-3">
            <i class="far fa-file-audio"></i>
            <h3>Native pronunciation</h3>
            <span class="icon-text">Hear your own words spoken back to you by a native English speaker! You can listen to their pronunciation, intonation, &mdash; everything that matters.</span>
          </div>
          <div class="col-md-3 my-3">
            <i class="far fa-comments"></i>
            <h3>Notes from teachers</h3>
            <span class="icon-text">Your teacher will provide you with notes to fix any mistakes and help you understand English grammar. You can get feedback for both your composition and performance.</span>
          </div>
          <div class="col-md-3 my-3">
            <i class="fas fa-clipboard"></i>
            <h3>Speech transcript</h3>
            <span class="icon-text">To help you plan your words, you can type in a transcript of your speech. Your teacher will return to you both the audio and a new corrected transcript for you to study.</span>
          </div>
          <div class="col-md-3 my-3">
            <i class="far fa-paper-plane"></i>
            <h3>Quick turn-around</h3>
            <span class="icon-text">You can expect that within 24 hours of submitting your speech, we will have the re-recorded audio and revised transcript ready for you. Speed is our specialty!</span>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="product-sample">
    <div class="container">
      <div class="row justify-content-center">
        <%= image_tag "front_page_speeches.png" %>
      </div>
    </div>
  </section>
  <section id="how-it-works">
    <div class="container">
      <h2>How it works</h2>
      <div class="row justify-content-center">
        <div class="col-12 col-md-6 my-3">
          <%= image_tag "voice-recording2.jpg" %>
        </div>
        <div class="col-12 col-md-6">
          <div class="steps">
            <div>1</div>
            <p>Write a transcript of your speech and any notes (in English or Japanese)</p>
          </div>
          <div class="steps">
            <div>2</div>
            <p>Record your voice using our app and send it to a teacher</p>
          </div>
          <div class="steps">
            <div>3</div>
            <p>Within a day, a teacher will re-record your speech and send it back</p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section id="reviews" style="background-image: linear-gradient(rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), url(https://res.cloudinary.com/dqco8z2dj/image/upload/v1646562338/speech1_ey4wuq.jpg);">
    <div class="container">
      <div class="row justify-content-center">
        <h2 class="mt-5">Satisfied customers</h2>
      </div>
      <div class="row">
        <div class="col col-12 col-md-4">
          <blockquote>
            <i class="fas fa-quote-left"></i>
            I was so worried when I had to give a speech in English as part of my class in university. In just one day, my speech was ready! I don’t have many foreign friends, so MyEnglishSpeech helped me practice with confidence. Thanks!
            <i class="fas fa-quote-right"></i>
            <cite>
              <%= image_tag "https://i.mydramalist.com/B4qqb_5c.jpg", class: "avatar" %>
              Yumi Ochiai, <br>
              university student 1st grade</cite>
          </blockquote>
        </div>
        <div class="col col-12 col-md-4">
          <blockquote>
            <i class="fas fa-quote-left"></i>
            I give academic lectures in English at international conferences several times a year, and textbooks just don’t have the field-specific words I need. This service allows me to be understood clearly by my peers in the scientific community.
            <i class="fas fa-quote-right"></i>
            <cite>
              <%= image_tag "https://i.mydramalist.com/B1xm5_5c.jpg", class: "avatar" %>
              Dr. Masaaki Amaha, <br>
              chemistry researcher</cite>
          </blockquote>
        </div>
        <div class="col col-12 col-md-4">
          <blockquote>
            <i class="fas fa-quote-left"></i>
            To reach a wider audience with my videos, I need English. But there are many cultural references and idioms that I need help translating for my foreign viewers. The teacher’s notes were so useful. Thumbs up for this app!
            <i class="fas fa-quote-right"></i>
            <cite>
              <%= image_tag "https://i.mydramalist.com/2Pl4E_5c.jpg", class: "avatar" %>
              Yasuaki "Yahoo" Ito, <br>
              Youtube talent</cite>
          </blockquote>
        </div>
      </div>
    </div>
  </section>
  <%# <section id="contact-us">contact us</section> %>
</div>

app/views/payments/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(	https://img.freepik.com/free-vector/payment-information-concept-illustration_114360-2886.jpg?w=1060);">
  <div class="container">
    <h1>Please confirm your order</h1>
  </div>
</div>
<div class="container-payments d-flex position-relative text-center">
  <div class="row py-2 mt-3">
    <div class="col">
    <%= image_tag "credit-card.png"%>
      <div class="row card_box text-center" >
        <p>Purchase of <strong><%= @order.speech.seconds %></strong> seconds of speech time for <strong><%= @order.speech.total_price %>円</strong> for the speech.</p>
        <p>Speech's title: <%= @order.speech.title %></p>
      </div>
    </div>
  </div>
</div>
<div class="row-button">
  <button id="pay" class="col-button col-6 btn btn-purple mb-3">Pay</button>
  <%= link_to "Cancel", speeches_path, class:"col-button col-6 btn btn-orange mb-3" %>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    const paymentButton = document.getElementById('pay');
    paymentButton.addEventListener('click', () => {
      const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
      stripe.redirectToCheckout({
        sessionId: '<%= @order.checkout_session_id %>'
      });
    });
  </script>
</div>

app/views/shared/_navbar.html.erb
<header class="header">
  <nav class="navbar p-0 navbar-expand-lg fixed-top navbar-lewagon">
    <div class="container">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "logo_transparent.png"%>
      <% end %>
      <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right"><i class="fa fa-bars"></i></button>
      <div id="navbarSupportedContent" class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Speeches", speeches_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "New Speech", new_speech_path, class: "nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <% if current_user.teacher?%>
                    <p class="nav-p">Profile: Teacher</p>
                  <% else %>
                    <p class="nav-p">Welcome <%= current_user.first_name %>!</p>
                  <% end %>
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/speeches/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)), url(	https://img.freepik.com/free-vector/job-interview-conversation_74855-7566.jpg?w=1800);">
  <div class="container">
    <h1>Your speeches</h1>
  </div>
</div>
<div id="index-body">
  <div class="container my-5">
    <h1 class="text-center py-3 index-title"> &mdash; Ready for correction &mdash;</h1>
    <div class="container-speech">
      <% @speeches.each do |speech| %>
        <% unless speech.title.nil? %>
          <% unless speech.current_status.include?("Corrected by") || speech.current_status.include?("Awaiting payment") %>
            <%= render 'speech_card', speech: speech %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <h1 class="text-center py-3 index-title"> &mdash; Pending payment &mdash;</h1>
    <div class="container-speech">
      <% @speeches.each do |speech| %>
        <% unless speech.title.nil? %>
          <% if speech.current_status.include?("Awaiting payment") %>
            <%= render 'speech_card', speech: speech %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <h1 class="text-center py-3 index-title"> &mdash; History &mdash;</h1>
    <div class="container-speech">
      <% @speeches.each do |speech| %>
        <% unless speech.title.nil? %>
          <% if speech.current_status.include?("Corrected by") %>
            <%= render 'speech_card', speech: speech %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="cards my-5">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(	https://img.freepik.com/free-vector/search-concept-landing-page_52683-11001.jpg?w=1480)">
        <%= link_to 'Home', root_path%>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(https://img.freepik.com/free-vector/microphone-sound-illustration_24908-61095.jpg?w=1060)">
        <%= link_to 'Recording', new_speech_url %>
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url(	https://img.freepik.com/free-vector/landing-page-credit-card-payment-concept_52683-25085.jpg?w=1380)">
        Payment
      </div>
    </div>
  </div>
</div>
</div>